name: Trivy Scan GHCR (Multiple Images - No Matrix)

on:
  schedule:
    - cron: "19 6 * * *"  # Runs daily at 6:19 AM UTC
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Run Trivy vulnerability scan for multiple images
        run: |
          images=(
            "ghcr.io/bsanchezmir/testv3/keycloak:21"
            "ghcr.io/bsanchezmir/testv3/nginx:1.23.4"
          )

          for image in "${images[@]}"; do
            echo "Scanning $image..."
            trivy image --severity CRITICAL,HIGH,MEDIUM,LOW --ignore-unfixed --format sarif --output "trivy-results.sarif" "$image"
          done

      - name: Upload Trivy scan results to GitHub Security tab (Single Category)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
          category: "trivy-production-images"  # Forces overwriting all scans into one report
