name: Trivy Scan GHCR (Matrix + CodeQL Merge SARIF)

on:
  schedule:
    - cron: "19 6 * * *"  # Runs daily at 6:19 AM UTC
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        image:
          - "ghcr.io/bsanchezmir/testv3/keycloak:26"
          - "ghcr.io/bsanchezmir/testv3/nginx:1.27"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set Safe Filename for SARIF Output
        id: sanitize_filename
        run: |
          SAFE_NAME=$(echo "${{ matrix.image }}" | tr '/:' '_')
          echo "SAFE_FILENAME=$SAFE_NAME" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ matrix.image }}"
          format: "sarif"
          output: "trivy-results-${{ env.SAFE_FILENAME }}.sarif"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          ignore-unfixed: true

      - name: Upload SARIF results as artifacts (Unique Artifact Names)
        uses: actions/upload-artifact@v4
        with:
          name: "trivy-sarif-${{ env.SAFE_FILENAME }}"
          path: "trivy-results-${{ env.SAFE_FILENAME }}.sarif"

  merge-and-upload:
    needs: scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Download all SARIF artifacts
        uses: actions/download-artifact@v4
        with:
          path: sarif-files

      - name: Move SARIF Files to Root Directory
        run: |
          echo "Moving SARIF files to a common location..."
          find sarif-files -type f -name "*.sarif" -exec mv {} sarif-files/ \;
          
          echo "Listing final SARIF file locations..."
          ls -lh sarif-files/*.sarif

      - name: Verify SARIF Files Exist Before Merging
        run: |
          if [ -z "$(ls -A sarif-files/*.sarif 2>/dev/null)" ]; then
            echo "❌ No SARIF files found. Merge cannot proceed."
            exit 1
          fi
          echo "✅ SARIF files confirmed."

      - name: Download and Extract CodeQL CLI
        run: |
          echo "Downloading CodeQL..."
          curl -Lo codeql.zip https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip
          
          echo "Extracting CodeQL..."
          unzip -q codeql.zip
          
          echo "Setting permissions..."
          chmod +x codeql/codeql
          
          rm -f codeql.zip

      - name: Check if CodeQL is Installed
        run: |
          echo "Checking CodeQL version..."
          ./codeql/codeql --version || echo "CodeQL execution failed"

      - name: Merge SARIF files with `codeql github merge-results`
        run: |
          echo "Merging SARIF files..."
          ./codeql/codeql github merge-results --sarif sarif-files/*.sarif --output merged-trivy-results.sarif

      - name: Upload Merged Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "merged-trivy-results.sarif"
          category: "trivy-production-images"
